console.log('hello world!');
console.log('hello nodejs!');
console.log(1000 + 1999);
console.log(setTimeout);
console.log(setInterval);
// console.log(requestAnimationFrame);
console.log(setImmediate);
console.log(process);
console.log(process.version);
console.log(process.versions);
console.log(process.kill);
console.log(process.exit);
console.log(process.pid);
console.log(process.cpuUsage());
console.log(process.memoryUsage.rss());
console.log(process.argv);
console.log(process.argv0);
console.log(process.stdin);
console.log(process.stdout);
console.log(process.platform);
console.log(process.arch);
console.log(process.send);
console.log(process.on);
console.log(process.title);
console.log(Date);
console.log(Math);
console.log(Math.random());
console.log(Math.abs(-199));